### ISSUE TITLE
Allow to configure which codes are included in the auto-suggest list

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#106]
Currently, the auto-suggest list shows only the codes authored by the user – nothing else. During the use of Open Ethnographer, the request came up that some users would like to see codes auto-suggested to them of another user (in this case, who also codes in that language).

We need a generic / systematic solution to this to make it a useful feature. So far, the proposal is as follows:

We would make it configurable (under User Settings) which codes to include in the auto-completion suggestions. The options would look like this:

> **Include suggestions from:**
> 
> (x) all topics
> ( ) topics with one of these Discourse tags: [___________________]
> 
> (x) all users
> ( ) the following users:  [____________________]
>
> (x) all languages
> ( ) my coding language
> ( ) my coding language and English

**Comment by tanius** [comment]
Blocked, because this is still [under discussion](https://edgeryders.eu/t/11038/5).

**Comment by tanius** [comment]
The decision is now to use the following mechanism to select which codes to include into the auto-complete list:

>  Ideally, when typing in codes in English, the box will display code suggestions from across the POPREBEL projects (so, by any other POPREBEL ethnographer, instead of only individual’s code or previous system where all codes from all projects were suggested). Depending on how the dual-code function works, suggestions in the native language should ideally include all codes that have been assigned in the project in that language. ([source](https://edgeryders.eu/t/13097/1))

So for the first version (which does _not_ need to be configurable), the auto-suggest list of codes should include:

* all codes appearing in topics tagged with the same `ethno-*` Discourse tags as the current topic, for example `ethno-poprebel`
* but only if they have a code name in the user's coding language or English

If a code has both a name in English and in the user's coding language, both names should be included into the auto-suggest list. Different from the current situation, the auto-suggest list will _not_ only show the user's own codes.

After that is implemented, we'll discuss here how to make this configurable.

**Comment by tanius** [comment]
Some more details that have not been clear yet:

**Code languages.** The autocomplete should list codes in the user's preferred language and in English. First include the codes with names in the user's preferred language. Then from the other codes also include those with English names. Show codes in the autocomplete list in the user's preferred coding language, and otherwise in English. If a code has both of these names, show both (though that is nice to have, not essential).

**Role of `ethno-*` tags.** These are technically just normal Discourse tags (not Open Ethnographer codes!). By convention, we use `ethno-*` Discourse tags to group together topics that belong to the same coding project, such as "POPREBEL". These topics should share the same code set in Open Ethnographer, which is the reason for this feature of adapting the autocomplete list.

**Comment by aerugo** [comment]
Will this solution also mean that the auto-suggest list of tags in the merge code view includes codes of others? 

Babel Between Us has turned out to be the most collaborative ethnography project we've had so far. We are already at 1300 annotations and the project has only just begun. There are five ethnographers working on the same corpus in the same language, and there is a lot of demand for being able to merge codes defined by different users.

**Comment by aerugo** [comment]
Thanks a lot for addressing this @damingo, it's looking a lot better now.
We seem to have a problem now with how parent and children codes get assigned ownership though. 

See the [two codes "walking"](https://bbu.world/annotator/codes?search=walking).

Bojan had already created a nested code [body → movement → walking](https://bbu.world/annotator/codes/851). I [applied it](https://bbu.world/annotator/text_annotations/1752) when annotating, selecting it from the drop-down list. This seems to have created a new code "walking", along with new parent codes "[movement](https://bbu.world/annotator/codes/850)" and "[body](https://bbu.world/annotator/codes/849)", with me as the creator.

**Comment by aerugo** [comment]
In fact, this seems to happen regardless of any nesting, [as with the code Mothe](https://bbu.world/annotator/codes?search=Mother)r that I just tried applying.

**Comment by damingo** [comment]
Oh, a misunderstanding... Will fix it now.

**Comment by damingo** [comment]
New version is now deployed.

**Comment by tanius** [comment]
The chosen solution is somewhat configurable, allowing to choose the Discourse tag from which to include the codes to propose. (That was needed because when coding for one project `ethno-a` and encountering a topic tagged `ethno-a` and `ethno-b` one only wants to see the codes proposed that appear in other `ethno-a` topics, not including those from other `ethno-b` topics.)

With that, we can consider this issue as resolved, as the other proposed bits of configuration either don't make sense in coding practice ("include codes via multiple Discourse tags", "include codes of the following users") or are already provided with a good default ("include all codes in my coding language and English").

**Comment by tanius** [comment]
> Show codes in the autocomplete list in the user's preferred coding language, and otherwise in English. If a code has both of these names, show both (though that is nice to have, not essential).

@damingo, please clarify how this was implemented. Does the list of proposed code include a code name only in the user's coding language, or additionally in English if both are available?

**Comment by damingo** [comment]
Code names in the autocomplete list are in the user's preferred coding language, if a code name is not available in the users coding language in English and if not available in English the codes first translation is used.
