### ISSUE TITLE
Fix "undefined method apply_resource_includes" in the Multisite installation

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#110]
There seems to be an issue with an incomplete bundle or similar in the Multisite installation of Open Ethnographer – not though in the edgeryders.eu installation. Symptoms: when clicking on any of "Codes", "Annotations", "Languages" in the Open Ethnographer main navigation, the following error message will appear:

> **Oops**
> The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.
> 
> Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it. […]

The Discourse error log indeed has information about it. For the three menu items, the logged error looks like this, respectively:

```
NoMethodError (undefined method `apply_resource_includes' for #<Annotator::AnnotatorStore::AnnotationsController:0x00007eff582d6f50>)
/home/discourse/production_multisite/shared/bundle/ruby/2.5.0/bundler/gems/annotator_store-gem-f809aba7b6d6/app/controllers/annotator/annotator_store/annotations_controller.rb:29:in `index'

NoMethodError (undefined method `apply_resource_includes' for #<Annotator::AnnotatorStore::TagsController:0x00007eff7457ed90>)
/home/discourse/production_multisite/shared/bundle/ruby/2.5.0/bundler/gems/annotator_store-gem-f809aba7b6d6/app/controllers/annotator/annotator_store/tags_controller.rb:21:in `index'

NoMethodError (undefined method `apply_resource_includes' for #<Annotator::AnnotatorStore::LanguagesController:0x0000564a1857fbd0>)
/home/discourse/production_multisite/shared/bundle/ruby/2.5.0/bundler/gems/annotator_store-gem-f809aba7b6d6/app/controllers/annotator/annotator_store/languages_controller.rb:10:in `index'
```

**Comment by damingo** [comment]
Fixed.
