### ISSUE TITLE
Fix that visiting code edit pages crashes the software

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#117]
When you go to a code show page of this software ([example](https://edgeryders.eu/annotator/codes/4975)) and then click on the top-right "Edit Code …" button, there will be a server error 500:

> **Oops**
>
> The software powering this discussion forum encountered an unexpected problem.

The Discourse error log says about this issue:

> ActionView::Template::Error (undefined method 'merge_tag' for #<AnnotatorStore::Tag:0x00007f6eccea2620>)
> […]/gems//activemodel-5.2.3/lib/active_model/attribute_methods.rb:430:in 'method_missing'
> […]/gems/administrate-0.13.0/lib/administrate/page/base.rb:35:in 'public_send'
> […]/gems/administrate-0.13.0/lib/administrate/page/base.rb:35:in 'get_attribute_value'
> […]/gems/administrate-0.13.0/lib/administrate/page/base.rb:29:in 'attribute_field'
> […]/gems/administrate-0.13.0/lib/administrate/page/form.rb:15:in 'block in attributes'
> […]/gems/administrate-0.13.0/lib/administrate/page/form.rb:14:in 'map'
> […]/administrate-0.13.0/lib/administrate/page/form.rb:14:in 'attributes'
> […]/gems/annotator_store-gem-ead8431647fb/app/views/annotator/annotator_store/tags/_form.html.erb:40:in `block in […]'
> […]

**Comment by damingo** [comment]
Fixed by the most recent commit.
