### ISSUE TITLE
Provide a fast way of editing code translations and descriptions

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#121]
## Editing code translations

Code names right now can be translated into multiple languages. It is not possible (right now, though people want it, see #137 ) to add a name and its translations on-the-fly when creating a code in the frontend. So coders will have to go to the backend later in order to add code translations. Right now, that is quite some click work.

We want to make this faster by a tabular "code translation" view in the backend of this software showing a list of codes with filters, just like the normal [list of codes](https://edgeryders.eu/annotator/codes). But the list format would be different, using a table with two columns for the code names. Both columns would be configurable as to what language version of the code names to show inside, and would default to the following:

* The left column, to English, which is the baseline language for code names that each code should have.
* The right column, to the user's preferred language from the settings.

The code names would be editable right in the table cells, making the code translation work really fast and comfortable. It also allows users to use a "code name / translated code name" convention of naming codes when creating them on-the-fly, and then later to split these names into the different language parts with the help of this code translation view.

## Editing code descriptions

In addition, users would like a comfortable and fast way to edit code descriptions. Originally it was requested to be able to do this on-the-fly in the frontend of this software (#121), but this was rather unworkable. Instead, we can just add a column with the code description field to the right of this code translation view, allowing to edit these descriptions with very little click work.

Comfortable editing of code descriptions is also relevant as preparatory work for the codebook feature (#119).

**Comment by damingo** [comment]
This is now implemented. To see the translation view go to "Codes" and select "View: Translate" in the upper right corner.
