### ISSUE TITLE
Provide a keyboard-only way of coding the same text selection again

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#122]
Currently, each Annotator.js annotation on text contains exactly one code. That makes sense to enable #120 without making the interface complex.

However, at the same time users want a fast way to code the same selection of text with a second, third etc. code, because that is a typical case. That would be possible without complicating the interface by allowing to create a second etc. code with keyboard action only. That's fast, because only mouse action is slow.

One idea how this could work:

1. Press <kbd>Enter</kbd> to save the first annotation.
2. Press <kbd>Enter</kbd> again to create a new Annotator.js overlay for adding another annotation on the same text.

If the text selection between these steps is kept intact, then this can be implemented as "pressing <kbd>Enter</kbd> when there is a text selection opens an Annotator.js editor for a new annotation". Then, coding a selection of text for the first time is also faster because one just has to select text and press <kbd>Enter</kbd> rather than select text and click the Annotator.js button.

**Comment by damingo** [comment]
Already implemented. It is now possible to create / assign multiple annotations at once in the annotations overlay.
