### ISSUE TITLE
Improve the user interface for merging codes

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#124]
Currently, for merging a code in the Open Ethnographer backend, one has to select a code from a dropdown list. Now we have so many codes (and possibly even of the same name) that this approach is no longer suitable. The dropdown will take a long time to even open!

Alternative proposal: using a textbox together with an auto-suggest list for code selection, behaving in the same way as in the Open Ethnographer frontend. Means, it should support multi-substring search, as implemented in #92.

**Comment by tanius** [comment]
Works great! Just that the auto-suggest list right now lists only the codes of the current user. It should instead be able to list all codes.

**Comment by damingo** [comment]
Fixed.
