### ISSUE TITLE
Allow deleting codes from the code showpage

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#125]
Currently, codes can only be deleted from the [list of codes](https://edgeryders.eu/annotator/codes) but not from the showpage of an individual code (like [this one](https://edgeryders.eu/annotator/codes/2750)). The latter should be supported as well, for example by showing a red "Delete" button in the top right. (On that note, "Delete" seems better than "Destroy" and should also be used in the [list of codes](https://edgeryders.eu/annotator/codes).)

**Comment by tanius** [comment]
This seems to be a really quick issue to solve. So @damingo, can you please implement this some time over the next days.

**Comment by damingo** [comment]
Done.
