### ISSUE TITLE
Fix the crash on annotation list pages

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#126]
## Bug description

The following scenario crashes the Open Ethnographer installation on the Edgeryders Communities sites right now: [listing the annotations of user Boja on bbu.world](https://bbu.world/annotator/annotations?creator_id=438).

The corresponding error message from the Discourse logs is:

> ActionView::Template::Error (undefined method 'path' for nil:NilClass) /home/discourse/production_multisite/shared/bundle/ruby/2.5.0/bundler/gems/annotator_store-gem-be56e4416466/app/models/annotator_store/tag.rb:57:in 'localized_name_with_path'

The crash seems related to one or a few annotations of that user, as listing annotations for other users works fine ([example](https://bbu.world/annotator/annotations?creator_id=458)), but [listing a certain page](https://bbu.world/annotator/annotations?page=5) of the global list of annotations results in the same crash.

## Possible causes

1. Possibly, this is only because the Edgeryders Communities sites don't have the latest version of the Open Ethnographer software yet. Updating it may just fix the whole thing already, as a lot of issues got fixed recently.

2. Otherwise, it's just a normal bug that would need fixing …

**Comment by damingo** [comment]
The reason was most likely cause 1.) as tags in a cache table were missing. This is now fixed and the code was adapted to be more fault tolerant. Annotations list pages will no longer crash if entries in the cache table are missing - this shall not happen anyway but makes it easier to debug.
