### ISSUE TITLE
Add useful filters to the topics list

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#133]
The current [list of topics](https://edgeryders.eu/annotator/topics) is not immediately useful as it shows all topics that exist on the platform, including the myriad of topics that have not annotations (and will not be annotated).

To make this list more useful, we would like to have two new filters added to the top bar:

* **Annotations.** Options would include:
    * all topics
    * with annotations *(default)*
    * without annotations
* **Tag.** For filtering by Discourse tag. This is needed because we use Discourse tags like `ethno-*` to mark which topics belong to a certain coding project. There could be a setting in this software to configure the prefix of tags to include in the list of filter options (such as `ethno-`). Alternatively, the filter might use a textbox with auto-complete to enter a Discourse tag name.

**Comment by tanius** [comment]
Implementation should wait until #222 is implemented, which will replace Discourse tag filters with project filters (or a similar concept) everywhere.

**Comment by damingo** [comment]
Already implemented. Now that projects are used instead of Discourse tags the tags filter is no longer needed and has been removed.
