### ISSUE TITLE
Add a Discourse tag filter to the codes list

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#135]
Similar to #133, we would like to have a filter for Discourse tags in the [list of codes](https://edgeryders.eu/annotator/codes). This is needed because we use Discourse tags like `ethno-*` to mark which topics belong to a certain coding project.

There could be a setting in this software to configure the prefix of tags to include in the list of filter options (such as `ethno-`). That setting would be the same as used in #133. Alternatively, the filter might use a textbox with auto-complete to enter a Discourse tag name.

**Comment by damingo** [comment]
Done.
