### ISSUE TITLE
Support creating code translations in the frontend

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#137]
Ethnographers requested the ability to select an existing English-language code for a highlighted portion of text and, at the same time, to be able to add a translation to it (in the user's preferred language, as configured under "[User Settings](https://edgeryders.eu/annotator/user_settings)").

Proposals how this could look like in the Annotator.js based frontend:

* Two boxes with an auto-complete function, the upper one for searching in English codes, and the lower one for searching codes in the user's preferred language. After selecting a code in one, the code's translation would appear in the other. If absent, it can be added at the time of coding.

* An icon next to the "edit" and "delete" icons to translate a code. So one would code with an existing code first (or create a new code on the fly), save that annotation, and _after_ that, click the "translate" icon in the Annotator.js overlay showing this annotation, to translate the code.

**Comment by tanius** [comment]
Currently blocked because we want to see first if #121 ("Provide a fast way of editing code translations and descriptions") solves the issue. That would be much simpler to implement.

**Comment by tanius** [comment]
@miahass: Still ok with the original proposal above that we first want to see if a dedicated grid-like UI for entering translations solves the issue of excessive click work to translate code names?

**Comment by miahass** [comment]
Definitely!

**Comment by tanius** [comment]
Removing the "important" label now because the alternative solution is now implemented via #121. Please evaluate that other solution and see if it suits your needs. If not, let us know in this issue. Otherwise we'll probably close this as "won't fix" in a few months.

**Comment by damingo** [comment]
Closing as proposed by @tanius.
