### ISSUE TITLE
Improve editing the parent code

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#139]
On a code's edit page ([example](https://edgeryders.eu/annotator/codes/3557/edit)), there is a field "Parent:", allowing to set or change the parent code of this code.

This is a dropdown, which is now no longer adequate given there are thousands of codes to select from. Instead, we'd like to have the same Select2 element here that is now used for merging codes (see #124). Like there, this element should be able to suggest all codes, not just the current user's codes.

**Comment by damingo** [comment]
Done. Handled the same way as for merging codes.
