### ISSUE TITLE
Fix that some annotations from merged codes are not visible in a code's annotation list

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#141]
After merging two codes, the annotations of the code that was selected in the dropdown to be merged do not appear in a code's annotation list. They do however appear in the count of the code's annotations in menu item "Codes", so they are not lost, just invisible.

It seems not to matter what names the codes had before merging. It happened with codes of the same name, but also of different names.

Example: [this code](https://bbu.world/annotator/codes/663) shows that it has "no annotations" on its details page. But the [codes overview page](https://bbu.world/annotator/codes) shows that it has five.

&nbsp;

Once this is fixed, please also tell that in [this topic](https://bbu.world/t/963).

**Comment by damingo** [comment]
This was fixed by #144
