### ISSUE TITLE
Add "merge" and "destroy" button to edit code view

### ISSUE THREAD

**Issue by skoteskote** [edgeryders/annotator_store-gem#142]
It's currently only possible to merge or destroy codes from the general code list, which makes it very difficult to merge codes since the user has to scroll through each page to find the code to merge. Best would be if the user could search for the code, and the merge button would appear next to the search result, just like it does in the list view.

**Comment by aerugo** [comment]
We've realized that this is actually extremely important in a complex project, we will use merging _a lot_. Giving access to that function from that view should be pretty easy right @damingo ?

**Comment by damingo** [comment]
True. I'll probably get it done today (Friday). But first have to fix #141 to make sure merging actually works.
