### ISSUE TITLE
Make search function show all codes including the search term

### ISSUE THREAD

**Issue by skoteskote** [edgeryders/annotator_store-gem#143]
Currently, the search code function only displays the result of exact matches, which makes it difficult and time-consuming to find the exact code, especially in regards to longer codes. It also needs the correct capitalization which is confusing.

It would be ideal if a user could put in "body", and the search function would show all codes including the word "body", regardless of if it's written "Body" or "body".

**Comment by aerugo** [comment]
This has been resolved.
