### ISSUE TITLE
Annotations disappearing while merging

### ISSUE THREAD

**Issue by skoteskote** [edgeryders/annotator_store-gem#144]
When I merge two codes from two different authors all annotations by the author of the merged code are lost, which makes merging somewhat pointless. 

Would it be possible to also get the annotations while merging codes?

**Comment by damingo** [comment]
Oh, I was just able to reproduce this and it seems to be that annotations are indeed deleted or at least not associated with the code after merging. I'm looking into this right now... Please do not use the Merge Code feature right now. I'll also deploy a new version right now that disables the feature to prevent further data loss in case annotations are really deleted.
