### ISSUE TITLE
Make the API endpoints access configurable in OE settings

### ISSUE THREAD

**Issue by aerugo** [edgeryders/annotator_store-gem#145]
In the Babel Between Us project, we have developed a codebook to display codes and descriptions publically. We have made it as an external Javascript app with its own design since BBU is an art project with some very specific design requirements. It takes a JSON formatted as [on the codes endpoint](https://bbu.world/annotator/codes.json) and displays it in a searchable and formatted list. This means that we need clientside access to that endpoint. 

After talking to @tanius, we agreed that the best solution will be to make the API endpoint access configurable in the OE settings.

**Comment by aerugo** [comment]
Assigning @damingo on advice from @tanius

**Comment by damingo** [comment]
Done. Endpoint access can be configured [here](https://bbu.world/annotator/settings).
