### ISSUE TITLE
Fix that the Annotator.js overlay button is no longer shown after the Discourse update

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#152]
After the update of the Edgeryders Communities platforms to the most recent Discourse version a few days ago, the Annotator.js overlay button does no longer show in the "Coding View" pages of topics on any of the Edgeryders Communities platforms.

It still shows for edgeryders.eu. So very probably indeed something to do with the recent update.

**Comment by damingo** [comment]
Fixed. Content-security-policy setting needed to be updated.
