### ISSUE TITLE
When merging a code the old code is not deleted.

### ISSUE THREAD

**Issue by skoteskote** [edgeryders/annotator_store-gem#153]
When I merge a code, the old code does not get deleted. It's annotations are moved to the merged code, but the old code still shows up, with the annotation number intact.

Example:
Merged code Mushroom (1) to Fungi (3).
Fungi gets all annotations from Mushroom, 4 in total.
Mushroom still shows in the code view with (1) annotation. 

Not a big issue but a bit confusing since I didn't know if the platform registered my merge at first.

**Comment by damingo** [comment]
Thanks for reporting this! Turns out a counter-cache column stopped being updated. This is now fixed. Will deploy the fixed version now.

**Comment by skoteskote** [comment]
Great! Thanks for fixing it
