### ISSUE TITLE
Provide the code merge UI on the code that is to be merged and then removed

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#156]
Currently, the user interface element to merge two codes is provided on the page of the code that is the _target_ of the merge operation. That has proven confusing. Instead, it should be provided on the page of the code that is to be merged into another code and the removed. The auto-complete box to select the target code would then be labelled "Code to merge into: [______]".

-----

Original report, now outdated after clearing up a misunderstanding in the discussion below:

~~When merges happen, the parent-child relationship disappears. If possible, it would be ideal to preserve the parent-child relationship of the code that remains (so, the one that been merged into).~~

**Comment by tanius** [comment]
@miahass: It appears that this issue requires the ability to store multiple parent codes for one child code (#162). Is that correct?

Or in more detail: assume we have the following parent codes A, B and their child codes C, D:

```
A  B
↑  ↑
C  D
```

After merging C into D, which node or nodes should be the parents of D?

**Comment by miahass** [comment]
It doesn't require multiple parent codes for one child code --- always keep the parent of the code that was merged into (so if C is merged into D, then the parent remains B). Most of the time, the child code should have the same parent anyway, or not have a parent at all (since if it's being merged, it means it's a duplicate or has similar meaning to the code it is being merged in to).

**Comment by miahass** [comment]
The other relationship that would be ideal to preserve is when merging parents, the parent code that was merged into takes the children of the code that was merged into it -- so if you merge A into B, then B should be the parent of both C and D.

**Comment by tanius** [comment]
> if C is merged into D, then the parent remains B

That is how the software behaves currently, but I think people mis-understand it (just happened to me as well). To merge code C into D, currently one has to go to the code page of D and select "Code to merge: C". See the note below that field that says:

> All annotations of the selected code will be assigned to this code and the selected code will be deleted.

So if that's the confusion then we should change the process to be as follows: "To merge code C into D, go to the code page of C and select 'Code to merge into: D'." Agreed?

> if you merge A into B, then B should be the parent of both C and D

Makes sense. @damingo please test how the system behaves right now, and implement this as requested.

**Comment by miahass** [comment]
So if that's the confusion then we should change the process to be as follows: "To merge code C into D, go to the code page of C and select 'Code to merge into: D'." Agreed?

Agreed!

**Comment by damingo** [comment]
Implemented - the new version will be uploaded tomorrow.
