### ISSUE TITLE
Allow grouping of users in user settings so they see each others codes as suggestions 

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#159]
Like the ability to see project-level codes in user settings (e.g. POPREBEL, NGI) which displays all project codes as suggestions, but instead designating another user. e.g. Jan and Wojt can see each others' codes as suggestions, but no one else's.

**Comment by miahass** [comment]
At the moment, it's only really important that users @wojt and @Jan are together, and @SZdenek @Jirka_Kocian are together. But that is important for them.

**Comment by damingo** [comment]
This is now implemented as "Propose codes from users" in "User Settings".
