### ISSUE TITLE
Display codes on one page in annotator

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#163]
Remove the 1, 2, 3 click through pages so that user can see all of their codes on one page.

**Comment by damingo** [comment]
To remove the pagination completely is not possible as it will result in long page load times when thousands of items are displayed. To lower the number of total pages I increased the items-per-page limit from 50 to 300 which still seems to be ok in terms of load time.
Will upload the fix later today.

**Comment by miahass** [comment]
Awesome, that’s great. That would definitely work well enough (so, happy to just have the issue closed when that’s implemented)
