### ISSUE TITLE
In the Search Codes feature the system is able to find codes only in the language set in User Preferences

### ISSUE THREAD

**Issue by VooVooVoo** [edgeryders/annotator_store-gem#166]
If the code has a translation (say it has its English name, a Polish translation and a Czech translation) and one's language is set to English, the system isn't able to find this code by its Polish or Czech name. We think it could be useful if it was able to do it.

**Comment by tanius** [comment]
Closing this in favour of #200, which is about the same issue but both for the backend code search and for the autocomplete widget for merging codes. Expect this to be solved soon now.
