### ISSUE TITLE
Mechanism to quickly assign codes based on existing annotations

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#170]
This is a feature request that came up in another discussion and was [endorsed](https://github.com/edgeryders/annotator_store-gem/issues/162#issuecomment-667709490) by @miahass. Here it goes:

We could introduce a mechanism that works on the list of existing annotations in order to quickly select some existing annotations from a filtered list and create new ones with the same quote text and a new code. That would allow fine-grained control when adding additional codes to coded content, while still being quicker than going through all the texts again. In comparison, copying an existing code and re-naming the copy is even quicker but does not allow fine-grained control, only an "all or nothing" approach of adding codes based on where existing codes are applied.

**Comment by damingo** [comment]
Already implemented.
