### ISSUE TITLE
When merging a parent code, transfer the child codes

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#171]
When merging a code A with child codes C into a code B, then the child codes C should be transferred to B as their new parent. Currently, that's apparently not done, so that C would have no parent after the merging is done (which removes code A in the end).

This was originally discussed [here](https://github.com/edgeryders/annotator_store-gem/issues/156#issuecomment-667651973):

>> ```
>> A  B
>> ↑  ↑
>> C  D
>> ```
> 
> The other relationship that would be ideal to preserve is when merging parents, the parent code that was merged into takes the children of the code that was merged into it -- so if you merge A into B, then B should be the parent of both C and D.

**Comment by damingo** [comment]
Done. Changes will be uploaded tomorrow.
