### ISSUE TITLE
Prevent codes with the same name and path but different authors

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#172]
These codes should probably not exist, but the database still has some (such as "tourism" ID 3131 and "tourism" ID 5520).

Existing codes that only differ by author should also be renamed by moving them below some parent code.

**Comment by tanius** [comment]
For @miahass to comment since I don't remember what the last desired kind of behaviour was for this matter. Should it be possible to have codes with the same name and path, differing only by author? If so, which code should be selected when entering the corresponding path for coding in the frontend?

**Comment by miahass** [comment]
Sorry for the delay here @tanius . It should not be possible (and in fact, I just came here to request that duplicates be automatically merged). 

The only metric I can think of for deciding is either a) the code that has a definition/description filled out; b) the code with the higher number of annotations or c) the code that was created first. But it really doesn't matter that much --- all that matters is that the duplicates are automatically merged together and the annotations from both are preserved.

**Comment by tanius** [comment]
>  It should not be possible

It's not possible to create such duplicate codes from within Open Ethnographer. I checked that a few days ago.

So what's left to do here is to merge existing codes that differ only by author, using options a) and then c) from what @miahass recommended above.

**Comment by damingo** [comment]
Done. In total 684 codes were merged into other codes.
