### ISSUE TITLE
Identical codes without discourse tag

### ISSUE THREAD

**Issue by katejsim** [edgeryders/annotator_store-gem#179]
Currently, OE shows in a drop down menu all existing codes. This is usually fine, but I realized that there are several codes that occur through various discourses: 

![Screen Shot 2020-08-25 at 12 28 06 PM](https://user-images.githubusercontent.com/55029800/91169845-ed2d2900-e6cf-11ea-9b8b-0d111d524e40.png)

This means that codes that are conceptually important and thus likely to occur in other discourses will get annotations across discourses.....as I find out re: #community building code. 

Is there a way to display discourse tag or the ethnographer name next to the code?

**Comment by miahass** [comment]
You should only be in the NGI Discourse category in your user settings and therefore should only be seeing the codes from NGI suggested to you. If there are duplicates it's because we have duplicate codes in NGI.

**Comment by miahass** [comment]
![image](https://user-images.githubusercontent.com/26431602/91172159-9f1a2480-e6d3-11ea-9b4d-13b837a700b8.png)

**Comment by miahass** [comment]
I've now merged the two codes "community building" in NGI into one, so you won't have this problem anymore with this particular code. If in future you do (before the auto merge) search the code in the backend under the NGI discourse tag and perform the merge.

**Comment by tanius** [comment]
>  If there are duplicates it's because we have duplicate codes in NGI, which is a different issue we are currently working to resolve.

Exactly, and this issue of pre-existing duplicates is now also solved as of 30 min ago.
