### ISSUE TITLE
View all codes added to a post

### ISSUE THREAD

**Issue by skoteskote** [edgeryders/annotator_store-gem#182]
So this is more of a feature request than an issue. For the way we code in the Babel project, **it would be super useful to have an easy way of seeing all codes applied to a post**. It would help my coding immensely. 

**Reason:** We are 8 people doing ethnography together, and often coding the same posts. Hence we need to be able to quickly see what other codes have been applied before adding our own. Currently, I have to hover over every sentence of the post and try to remember all the codes applied, which isn't ideal for shorter posts, and not possible for longer posts. This leads to a lot of duplicate codes, different phrasings meaning the same thing, that then needs to be merged. 

A quick sketch of how it might look:
![OE-allcodes](https://user-images.githubusercontent.com/11414586/91282322-7d7b7480-e789-11ea-8b20-fba2ad6962fd.jpg)

**Comment by tanius** [comment]
Thank you for the detailed proposal. I'd like to postpone this for some weeks until we get confirmation of some budget adjustments we applied for. But if @miahass thinks this is important for progress in the coding, we can probably make it happen somehow.

**Comment by miahass** [comment]
Assigning as important since many users are now requesting this as an important feature. I would prioritise this second after the drag and drop / checkbox hierarchy organisation.

**Comment by miahass** [comment]
@tanius, what would it cost to implement this and number #203 ? Both have become really important. I can find budget if needed.

**Comment by tanius** [comment]
Ok, a sidebar or other permanently visible UI element for each post (not just once per topic) that lists all codes already applied to that post by others.

The Open Ethnographer user setting "Discourse tag" is not relevant here, as it's not about showing codes from the same ethnographic corpus, just those applied to the same post already (so always from the current post's ethnographic corpus).

However, the Open Ethnographer user setting "Propose codes from users" is relevant. When configured, it should act as an additional filter on the codes to be shown in the sidebar, showing only those created by the specified users plus the author's own codes. (If this user setting is not useful in practice, please let us know @miahass. No good in unnecessarily complex software.)

Another thing to keep in mind is that there is are no access rights for codes in Open Ethnographer. Annotations are protected as being part of protected categories, but so far anyone's codes can be seen by anyone else on the platform.

What would be a rough worktime estimation for getting this done, @damingo?

**Comment by damingo** [comment]
All referenced codes are now displayed at the right side of a post. 

> However, the Open Ethnographer user setting "Propose codes from users" is relevant. When configured, it should act as an additional filter on the codes to be shown in the sidebar, showing only those created by the specified users plus the author's own codes. (If this user setting is not useful in practice, please let us know @miahass. No good in unnecessarily complex software.)

This is not yet implemented as we were not sure of its usefulness - it might be confusing when not all codes are listed in the sidebar. If desired it can still be implemented.
