### ISSUE TITLE
Translations don't show

### ISSUE THREAD

**Issue by VooVooVoo** [edgeryders/annotator_store-gem#184]
1. Since the latest large update and transfer of definitions to OE backend I cannot make the system show Polish translations of codes from before the update in the usual place (next to their English names). They show here:
![code issues2](https://user-images.githubusercontent.com/20644443/91746098-5b845680-ebbc-11ea-8d7c-90e547c692a3.png)

But not here:
![code issues](https://user-images.githubusercontent.com/20644443/91746104-5cb58380-ebbc-11ea-8374-131c41dbfdf6.png)
Sometimes they do this:
![code issues3](https://user-images.githubusercontent.com/20644443/91746136-6b9c3600-ebbc-11ea-8fea-58fddb0949c8.png)
(And I'm pretty sure I translated this one)

Or this happens:
![image](https://user-images.githubusercontent.com/20644443/91747435-78218e00-ebbe-11ea-9732-813319bb6aa6.png)
This one has a Polish translation, I can find it when I conduct a search via the Search Codes feature when my language is set to Polish (it's nuda in Polish), but here it seems as if it didn't have a Polish translation (I know it says "Showing 5 out of 7" but why not Polish?):
![code issues 4](https://user-images.githubusercontent.com/20644443/91753611-6e9d2380-ebc8-11ea-99b7-15bb775b070f.png)

2. Some codes don't show at all if I use the Search Codes feature in English and with English set in my User Preferences, e.g.:
![Code issues 5](https://user-images.githubusercontent.com/20644443/91751746-9939ad00-ebc5-11ea-82c2-d3e3bfce2a74.png)
But I am able to find them when I switch to Polish (and their Polish name):
![code issues 6](https://user-images.githubusercontent.com/20644443/91753551-57f6cc80-ebc8-11ea-9c63-08b4dd63d2a6.png)

I think the same pertains to Czech translations.
And I'm pretty sure I lost some of my translations somewhere in the process (I mean I'm pretty sure that some of the codes that don't have a Polish translation now used to have it; no matter, I'm going through the whole list and checking, adding where necessary)

**Comment by damingo** [comment]
Thanks for the detailed issue report. Translations were indeed not created when duplicate codes were merged. This is now fixed and 62 missing translations were created. The other issues mentioned shall now also be fixed. A cache table (Localized Tags) got out of sync after the import of codes.
