### ISSUE TITLE
POPREBEL - coding: Non-English translations (Czech, Polish) of code names disappeared

### ISSUE THREAD

**Issue by ZdenekS-POPREBEL** [edgeryders/annotator_store-gem#189]
Hello Mathias(?),

after last debug of the Open Ethnographer (probably allowing to merge any codes without the need of being owner of the codes), Czech and Polish names of codes dissapeared, and only English versions of the code-names are now in the back-end. (Unless, the Czech code was used by both Czech coders, then the Czech mutation of the code's name stayed int he system. Or at least this is my explanation why there are some bilingual codes.)

Can you please return the Czech (and Polish) labels/code-names back to the coding system. Otherwise, we would have to do it manually, code by code.

Thank you, Zdenek

**Comment by damingo** [comment]
Turns out that translations were indeed deleted. A temporary fix for the "Translate View" is already deployed to make sure no additional translations get deleted. I'll restore deleted translations from backups later today.

**Comment by damingo** [comment]
Non-English translations are not restored. 402 in total (Czech: 286, Polish: 93, Serbian: 14, German: 9).
