### ISSUE TITLE
Search Function in Open Ethnographer excludes " and ' -- revert to old search function

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#194]
We have a lot of codes that begin with a single or double apostrophe and that don't come up when searching the name of the code.

 I think someone requested to change the search function to only codes that start with the string inputted before which is how we got to where we are now, but upon observation I think we need to return to the older search -- where any part of the word displayed all of the codes that contained it. Because losing the ones that begin with quotes is problematic now. Thank you

**Comment by miahass** [comment]
same goes for the suggestion function when coding

**Comment by tanius** [comment]
Seems reasonable and a small enough task to fit in. Over to @damingo for implementation :) 

What we want in the end is, I think, a multi-substring search, using space-separated substrings as input, and requiring a match in the same order (which is relevant for quickly selecting from code hierarchies when using the suggestion function).

So for example, with the search string `home cook`, the following would be matches:

* home-based activities → eating and cooking
* home-based activities → kitchen → cooking

but the following would not be a match:

* cooking at home

**Comment by miahass** [comment]
Would that solution still allow for words with quotation marks at the beginning of the word to be found using the word without quotes? 

For example, when I search: cook I would want: cooking, 'cooking at home' and "cooking at home" to also appear, if they exist.

**Comment by tanius** [comment]
Yes, matches would not be limited to the start of words (where "words" means "space-separated strings").

**Comment by damingo** [comment]
Done. (New version will be uploaded today.)
