### ISSUE TITLE
Allow to create child codes on-the-fly

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#195]
To enable better separation between the codes for different coding projects (see #193) we want a way to create child codes on-the-fly. Currently, only top-level codes can be created on-the-fly while coding, by entering the name of the code to create into the Annotator.js popover window in the Open Ethnographer frontend.

Proposal: entering any of the following strings should result in creating a code `childcode` with parent `parentcode`:

* `parentcode -> childcode`
* `parentcode → childcode` (using the "arrow right" character that we already use as level separator in code paths)

If `parentcode` does not exist, it should be created on-the-fly as well. And the same system should also work with any number of levels.

I thought we had this functionality already, but apparently not. What we have so far is to *apply* existing child codes when entering the code path of the hierarchy, with a right arrow to separate the levels, such as in `parentcode → childcode`.

**Comment by miahass** [comment]
Silly question, sorry, but how do you create the "arrow right" on the keyboard?

**Comment by tanius** [comment]
You'll not be supposed to type an arrow right character, but rather <kbd>-</kbd> <kbd>></kbd> (minus, greater), resulting in an approximate arrow `->` that will be automatically converted to the proper Unicode symbol when saving the annotation.

If you're interested in really typing arrow right: it depends. A lot. Basically look up how typing Unicode characters that are not on the keyboard works in your operating system. Windows has the <kbd>Alt</kbd> + codepoint number system, I believe. Or in my case under Linux, I type <kbd>[Compose](https://en.wikipedia.org/wiki/Compose_key)</kbd> <kbd>-</kbd> <kbd>></kbd>. There are seemingly ways to enable a Compose key also under macOS and Windows, should you like that system. (It's my absolute favourite for entering all those special characters. Here are some of those I type with compose key sequences regularly: ◂ ▸ © 〈〉… → 🡑🡓🡒🡐 – — ± ≥ ≤ ß »« “ ” )

**Comment by damingo** [comment]
Child codes can now be created on-the-fly with ``parentcode -> childcode``. The whitespaces before and after the ``->`` are not required. So ``parentcode->childcode`` also works.
