### ISSUE TITLE
Add a "post author" field to the annotation endpoint?

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/annotator_store-gem#201]
Currently the annotation endpoint returns the `post_id`. One has then to look at the post endpoint to find out other characteristics of the post. 

One of these characteristics, the ID of the post's author, is important for an algorithm to reduce the codes co-occurrence network. Looking up the post for each annotation makes computation via Python quite slow. How easy is it to add a `post_author_id` field to the *annotation* endpoint?

**Comment by tanius** [comment]
Seems like an easy fix. Over to Daniel for implementing this. Deployment within 7-10 days will be ok.

But let's call the additional field `post_creator_id`, in line with us using `creator_id` to identify the user who created the annotation.

Also when done, this new field should be documented in the [annotations.json API docs](https://edgeryders.eu/t/using-the-edgeryders-eu-apis/7904#heading--3-2).

**Comment by damingo** [comment]
The field is now available as  ``post_creator_id``. 
Added it to the annotations.json API docs.
