### ISSUE TITLE
Sort by number of annotations

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#203]
In the sort by drop down in the "codes" backend, provide an option to sort by number of annotations. 

![image](https://user-images.githubusercontent.com/26431602/106169022-d57a3500-6186-11eb-9879-cf3f9b57c61c.png)

**Comment by tanius** [comment]
This should be straightforward and fast to implement, so we won't need added budget for it.

I think sorting by number of annotations should be a tree sort, sorting all the branches separately. Codes would still be shown as a hierarchy. The number to use for parent codes should be the total, incl. uses of the child codes. So in the case of "accessibility (48 + 2)" above, the sort criterion to use would be 50. This makes sure that often-used child codes appear high up in the list by pushing their parent element high up.

**Comment by damingo** [comment]
There is now an additional sort option "Sort by: Number of annotations". Codes with the most number of annotations are displayed first. Each branch is sorted separately. 
As discussed with @tanius we decided that the sort order of parent codes does not factor in child codes (as proposed in @tanius comment above). If this is important it can still be implemented, but will require several hours of work as code will need to be rewritten.
