### ISSUE TITLE
Support moving codes to the top level using bulk-editing mode

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#204]
The recently deployed [bulk editing mode](https://github.com/edgeryders/annotator_store-gem/issues/4) for codes allows to move a selection of codes as child codes under a single other codes.

A small enhancement to this system has been requested by @miahass. Namely, the list of parent codes to move the codes under should also have an option to move them to the top level, that is, to select "no parent" in some way.

**Comment by damingo** [comment]
This is already possible by leaving the field blank. I add a hint to the form-field to make this clear.
