### ISSUE TITLE
Discourse Tag filter for annotations

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#212]
To support comfortable splitting of existing codes and their annotations, we need a filter by Discourse tag in the "Annotations" section of Open Ethnographer. Just like the filter in the top left of the "Codes" section, which allows to select a single `ethno-…` Discourse tag to filter by.

This filter allows to comfortably select from a code's annotations by the project they belong to and to move them to another code. Of course this needs a "move annotation" feature, which is handled in different issues (#214, #215).

**Comment by damingo** [comment]
Done.
