### ISSUE TITLE
Show annotations more compactly in lists

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#213]
The ["Annotations" section](https://edgeryders.eu/annotator/annotations) of the Open Ethnographer backend shows all annotation with the full text they are applied to (column "Quote"). Since that quote tends to be long, it leads to a very long annotations list that is difficult to navigate.

This list should be shown more compactly by shortening the "Quote" column as follows: the first five words, then "space, ellipsis, space" ("` … `"), then the last five words of the quote. The full quote is still visible by going to the annotation's detail page.

**Comment by damingo** [comment]
Quotes are now shortened in the list of annotations. The complete quote can be seen by hovering with the mouse over the shortened quote.
