### ISSUE TITLE
Action to move an annotation

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#214]
To make splitting existing codes and their annotations comfortable, we'd like to introduce an action "Move" for annotations. Currently, annotations shown in the "Annotations" section of backend only have an action "Destroy" listed behind them, and editing an annotation in the backend also does not allow to change the annotation's code (that is, to move it).

Moving should mean to change to which code the annotation is assigned.

There should also be a bulk action to move annotations, but that will be handled in its own issue (#215).

**Comment by damingo** [comment]
Done.

**Comment by tanius** [comment]
To note, this has been implemented by making the "code" value editable on the edit pages of annotations. There is no "Move" action behind every annotation in annotation lists (unlike for the "Destroy" action), but this is ok.
