### ISSUE TITLE
Fix the code sort order

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#219]
It seems that the function to sort codes in the [codes list](https://edgeryders.eu/annotator/codes) does no longer work properly, possibly as a side effect of the recent change how code trees are rendered. I could not find a configuration where the sort order feature still works, but there are at least two different bugs involved:

* When the "Creator" filter is used, changing the sort order has no effect at all.
* When no filters (neither "Discourse Tag" nor "Creator") are used, the sort order of first-level codes without child codes appears correct, but codes that do have child codes appear in apparently random positions in the tree. This might be because they appear now in the positions of one of their child elements, as child elements are now internally expanded to include their ancestors in the recently modified tree rendering system.

**Comment by damingo** [comment]
Now works again. The issue was caused by how the code tree is rendered.
