### ISSUE TITLE
Annotation usage counted wrong for copied code

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#220]
When copying a code that has at least one annotation, the result will be a code shown in the [code list](https://edgeryders.eu/annotator/codes) as having twice the annotations than the original. When copying the copied code again, the result will be a code shown as having three times the annotations of the original, and so on.

This is only an error of counting the annotations, not of actual annotations assigned to the new codes. Because when looking at the list of annotations of such a copied code, only the same number of annotations are present as were available for the original code, but assigned to the copied version. That is as intended.

**Comment by damingo** [comment]
Resolved. Wrong counts have also been fixed.
