### ISSUE TITLE
After deleting a code, the code's HTML page does not display that a 404 error has occurred

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/annotator_store-gem#234]
For example: 

https://edgeryders.eu/annotator/codes/9634

returns a blank page, which is confusing. 

Compare: 

https://edgeryders.eu/annotator/codes/9634.json

**Comment by damingo** [comment]
For HTML pages a page with "Page not found." is now displayed.

**Comment by damingo** [comment]
Now the JSON page needs better error handling. I will fix it...

**Comment by damingo** [comment]
Now fixed.
