### ISSUE TITLE
Fix Server Error 500 when editing or creating user settings

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#236]
In at least the one specific case below, trying to edit the Open Ethnographer user settings leads to a "Server Error 500":

1. Log in with any admin user or user in the [Annotator group](https://community.trustinplay.eu/g/Annotator) into [community.trustinplay.eu](https://community.trustinplay.eu/).

2. Go to the Open Ethnographer [user settings list](https://community.trustinplay.eu/annotator/user_settings).

3. Click on "New User Settings", or click on "Edit" for an existing user setting. Both leads to a Server Error 500 currently.

**Comment by tanius** [comment]
This can be fixed by renaming the Discourse group's name from `Annotator` to lowercase `annotator` (via an intermediate rename to something else, as Discourse will complain about the name being in use otherwise).

The real solution is obviously to accept both `annotator` and `Annotator` (and any other case variation spelling!) as the group used for access authorization. Makes sense, as the rename behavior in Discourse shows that Discourse considers spelling variants that differ only in case as equivalent. When a group using one such variant exists, no group using a second such variant can be created.

So, keeping this open for now. But use the `annotator` group name as a workaround for now.

**Comment by damingo** [comment]
Now fixed
