### ISSUE TITLE
Fix Server Error 500 when copying codes

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#237]
On the openethnography.net site (and so far only there), trying to use the "Copy" feature for a code leads to a Server Error 500 as of writing this. How to reproduce:

1. Log in with any user in the [Annotator group](https://openethnography.net/g/annotator) into [openethnography.net](https://openethnography.net/).

2. Go to the [Open Ethnographer code list](https://openethnography.net/annotator/codes), showing all codes by all creators.

3. Click "Copy" in the action links behind any code. This leads to a Server Error 500 currently, without a code being copied.

The same issue also happens on the [community.trustinplay.eu](https://community.trustinplay.eu/) platform, and probably on all the other Edgeryders Communities platforms except edgeryders.eu, since all those share the same Discourse Annotator installation.

**Comment by damingo** [comment]
Turns out not all database migrations were run. Now fixed.
