### ISSUE TITLE
Fix Server Error 500 when showing a topic with annotations

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#240]
This issue happens on the [community.trustinplay.eu](https://community.trustinplay.eu/) platform, and probably on all the other Edgeryders Communities platforms except edgeryders.eu, since all those share the same Discourse Annotator installation.

Steps to reproduce:

1. Log in on community.trustinplay.eu with a user that is in the [Annotator group](https://community.trustinplay.eu/g/Annotator).
2. Go to the Annotator coding interface of a topic that does not yet have annotations.
3. Create an annotation.
4. Reload the topic. This will lead to a "Server Error 500" message.

When the above error happens, the following is found in the Discourse Error Log:

```
ActionView::Template::Error (undefined method `revision_number' for 
#<DiscourseAnnotator::TextAnnotation:0x00007f8930475f48>)
```

And this backtrace is shown:

```
activemodel (6.1.3.2) lib/active_model/attribute_methods.rb:469:in `method_missing'
discourse-annotator (ae05461e295e) app/views/annotator/posts/_post.html.erb:8
actionview (6.1.3.2) lib/action_view/base.rb:247:in `public_send'
actionview (6.1.3.2) lib/action_view/base.rb:247:in `_run'
actionview (6.1.3.2) lib/action_view/template.rb:154:in `block in render'
activesupport (6.1.3.2) lib/active_support/notifications.rb:205:in `instrument'
actionview (6.1.3.2) lib/action_view/template.rb:345:in `instrument_render_template'
actionview (6.1.3.2) lib/action_view/template.rb:152:in `render'
```

**Comment by damingo** [comment]
Turns out not all database migrations were run. Now fixed.
