### ISSUE TITLE
"Code with Open Ethnographer" button below Discourse topic titles leads to a wrong URL

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#241]
The URL format is still the one from before the projects feature #222. These URLs do not work anymore.

As a workaround, you can **(1)** go to the [main Annotator interface](https://edgeryders.eu/annotator), **(2)** select your project in the top left dropdown, then **(3)** go to "Topics" in the left sidebar and **(4)** search for the desired topic by its title, using the top-right search box.

**Comment by damingo** [comment]
All "Code with Open Ethnographer" links on all sites that use discourse-annotator are now updated.
