### ISSUE TITLE
Document the latest Open Ethnographer API

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#245]
The [project feature](https://github.com/edgeryders/discourse-annotator/issues/222)  has been deployed for some time now and works well, but we missed documenting the changes to the Open Ethnographer API.

@damingo, please document the changes in the [Edgeryders API Manual](https://edgeryders.eu/t/7904), or alternatively outline the API interface here and I will change the manual accordingly.

I already found out some bits and pieces:

1. To obtain the list of all projects and their IDs:

    ```
    curl -X GET "https://edgeryders.eu/annotator/projects.json" -H "Api-Key: 11e3b…"
    ```

2. To obtain annotations that belong to a certain project:

    ```
    curl -X GET "https://edgeryders.eu/annotator/annotations.json?project_id=1" -H "Api-Key: 11e3b…"
    ```

But I cannot get the `https://edgeryders.eu/annotator/codes.json` to work anymore, even when providing a `project_id` parameter.

**Comment by damingo** [comment]
API manual is now updated. Can be closed if it's all good.
