### ISSUE TITLE
Provide a more efficient interface to edit Open Ethnographer code hierarchies

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#4]
Currently, the [interface to edit Open Ethnographer codes](https://edgeryders.eu/annotator/codes) allows to edit their hierarchy by selecting a parent tag from a list. At some point, this should be improved to be more efficient.

Proposal: Use a drag & drop system. Dropping a code on another code would mean to assign it to that latter code as its new parent (moving it in the hierarchy "below that code").

**Comment by miahass** [comment]
Also could use a select function (so tickboxes) to select multiple codes to add as children to the same parent. Or even just ability to  select multiple codes to add to a parent, on the code page of the parent code.

**Comment by tanius** [comment]
Actually, the comment by @miahass above makes a lot of sense – a drag & drop interface like I proposed in the original post above does not make sense because the code list covers multiple pages, so drag&drop to any other code in that long list is not properly possible.

We already use an auto-complete assisted dropdown to choose the parent code in the code edit page. So the new proposal is to add a section "children codes" on code edit pages and a similar auto-complete assisted dropdown to select them. In contrast to the dropdown to select the parent code, it would be possible to select multiple ones, either as "bubbles" in a line, or by adding another autocomplete below once one is filled.

**Comment by miahass** [comment]
![image](https://user-images.githubusercontent.com/26431602/106167045-b5e20d00-6184-11eb-89fe-098d9231185d.png)

**Comment by aerugo** [comment]
@damingo - how long do you think it would take to implement the above?

**Comment by tanius** [comment]
I just discussed this issue with Daniel and this is his assessment (slightly edited for clarity):

> For the codes list page, there are already different views, namely the normal one and the bulk translate view. So this feature would become another view "Bulk Editing", with a form a the top "Assign selected to parent:", with a field to select one code from an autocomplete-enabled dropdown.
> 
> That seems rather simple. For pagination, the selected items need to be saved in the session or forwarded to the next page. In total, it means adding one controller action, one form, and fixing some bugs. I think that's the best option to implement this. On the code editing pages on the other hand, the UI for this feature would be too restricted in space to select codes comfortably.
>
> Time: maybe 4-8 hours, plus uncertainty.

Ok then, let's just get this done from the remaining IT support budget. Over to @damingo for implementation. When foreseeable time usage goes beyond 10 hours, please let me know to re-evaluate.

**Comment by damingo** [comment]
Now deployed. Accessible as "Bulk Editing" in the top-right "View" menu.
Note: Codes stay selected when one uses the pagination at the bottom of the page. So it is possible to select codes on multiple pages and then use the "Assign selected to parent" action. All selected codes from all pages will be assigned to the selected parent code.
