### ISSUE TITLE
Create a report for monitoring coding activities with Data Explorer

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/annotator_store-gem#58]
Managing research entails keeping an eye on what the ethnographers are doing across the different projects. It would be great to have a few reports in the "Admin" section of Discourse.

* Number of annotations per day per project and per author
* Count of annotations per project and per author

**Comment by albertocottica** [comment]
Can I ask @tanius  to also add 

* count of codes per project
* count of codes per author

**Comment by tanius** [comment]
Also done now, see:

* [count of codes per project](https://edgeryders.eu/admin/plugins/explorer/?id=7) (rather, by category as a proxy for project)
* [count of codes per author](https://edgeryders.eu/admin/plugins/explorer/?id=6)
