### ISSUE TITLE
Fix that the Coding View link does not work on Communities platforms

### ISSUE THREAD

**Issue by tanius** [edgeryders/annotator_store-gem#99]
It seems that not all relevant code got migrated out of [our Discourse fork](https://github.com/edgeryders/discourse) and into this repository, because the "Coding View" link appears on and works on the edgeryders.eu topic pages but does not on the pages of any of our Communities platforms.

To test, I had set up a group `annotator` on a Communities platform, added myself to it, and then added this code to the `</head>` section of the Discourse template, as seen in the edgeryders.eu template:

```
<script type='text/x-handlebars' data-template-name='/connectors/topic-above-posts/open-ethnographer-link'>
  {{#if currentUser.annotator}}
     <a class="icon" href="?oe=1" title="Visit the Open Ethnographer coding view." target="_blank"><i class="fa fa-tags"></i> Coding View</a>
  {{/if}}
</script>
```

That should make the "Coding View" link appear, but does not. Removing the `if` statement from the code above will make the link appear, but the forwarding does not work then – it will just display the same page.

So it appears that the following code pieces do not work in the Communities sites:

* `currentUser.annotator`
* the code catching the forwarding from URLs like `https://example.com/t/123?oe=1` to URLs like `https://example.com/annotator/topics/123`

**Comment by damingo** [comment]
Fixed.
